version: '3.1'

services:
  django:
    container_name: lms
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code/
    ports:
      - "8011:8000"

  postgres:
    container_name: db
    image: postgres:16.3
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5532:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
